-- SEO Scoring Rules Data
INSERT INTO seo_rules (rule_name, category, weight, min_value, max_value, optimal_value, is_active, description) VALUES
('Title Length', 'title', 15.00, 30, 70, 60, 1, 'Optimal title length for SEO'),
('Title Has Keywords', 'title', 15.00, NULL, NULL, 1, 1, 'Title should contain target keywords'),
('Title Uniqueness', 'title', 15.00, NULL, NULL, 1, 1, 'Title should be unique across site'),
('Description Length', 'description', 15.00, 120, 160, 155, 1, 'Optimal meta description length'),
('Description Has Keywords', 'description', 15.00, NULL, NULL, 1, 1, 'Description should contain keywords'),
('Keyword Density', 'keywords', 10.00, 1, 3, 2, 1, 'Keyword density should be 1-3%'),
('Keyword Placement', 'keywords', 10.00, NULL, NULL, 1, 1, 'Keywords in title, h1, first paragraph'),
('Content Length', 'content', 20.00, 300, 3000, 1000, 1, 'Optimal content length'),
('Content Readability', 'content', 20.00, 60, 100, 70, 1, 'Flesch reading ease score'),
('Content Structure', 'content', 20.00, NULL, NULL, 1, 1, 'Proper use of headings'),
('Content Freshness', 'content', 20.00, NULL, NULL, 1, 1, 'Recently updated content'),
('URL Length', 'url', 10.00, 10, 60, 40, 1, 'Optimal URL length'),
('URL Structure', 'url', 10.00, NULL, NULL, 1, 1, 'Clean, descriptive URL structure'),
('URL Has Keywords', 'url', 10.00, NULL, NULL, 1, 1, 'URL contains target keywords'),
('Image Alt Text', 'images', 10.00, NULL, NULL, 1, 1, 'All images have descriptive alt text'),
('Image Optimization', 'images', 10.00, NULL, NULL, 1, 1, 'Images are optimized for web'),
('Image Count', 'images', 10.00, 1, 10, 3, 1, 'Optimal number of images'),
('Internal Links', 'links', 10.00, 2, 10, 5, 1, 'Number of internal links'),
('External Links', 'links', 10.00, 1, 5, 2, 1, 'Number of external links'),
('Link Quality', 'links', 10.00, NULL, NULL, 1, 1, 'Links to authoritative sources'),
('Readability Score', 'readability', 10.00, 60, 100, 70, 1, 'Flesch reading ease'),
('Paragraph Length', 'readability', 10.00, 50, 150, 100, 1, 'Average paragraph length')
